version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - FaKeller
  ignore:
  - dependency-name: ajv
    versions:
    - 7.0.3
    - 7.0.4
    - 7.1.0
    - 7.1.1
    - 7.2.1
    - 7.2.3
    - 8.0.1
    - 8.0.3
    - 8.0.5
    - 8.1.0
  - dependency-name: ajv-cli
    versions:
    - 4.0.1
    - 4.1.0
    - 4.2.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: inversify
    versions:
    - 5.0.5
  - dependency-name: lodash
    versions:
    - 4.17.20
