language: node_js
node_js:
- node
- lts/*
cache:
  yarn: true
script:
- yarn run build
- yarn test
- yarn run package
deploy:
  - provider: releases
    api_key:
      secure: HJWvKmGYIdtu+eWj00p53dlp7VVnMsYlBe71vsEiQPZmPahJjwMj1pkRY0i6gLooZTZl9zcp+r/M7v8unYd0cuNo3q4YLD52sPKqIRaebpRDA3gqusUhoC4tL0zG6i+HiG3jSj+juiz8y006DoDbYydOCKf/RoIJSxVYLW/6rB5P8vMpPDeIgH/nxTLGcpxWfQ/UFCoV5fWw8oYrajPxeezqXZPB6EJOkZcZ0mAB5BbG4WueSvkHlLJT0byzjiOotvd3FdsnP+eLc41Dz4luuQaw9/fJ3twxOb2wsHBkAzhWFvGDut3F0n5u2T0GK224OGBCWz4xZ16Xad2DvXYWGOO0xojPhhqW+q0VeMZtoyeebePwA2Oxpe/us4undtXNQuGWtYYcnh7lY5VypeLiXLakdLAg5g9zZBQFNdZWb4F/Jiwz8ByI00ErYNTBcmmYTvldWSpZbBQQrtI9XAbzIBrujHNYHhPbAoSShhCgaIB3DRDhr01zmoHWKSwV4KuAXHphkfA++qksAUmBKWipTNfk+XLm+5hyXxWwCkv2sD5EbRy93pDr7nqJtdJi6f+5O3X6YVxeJ9Mk/8JOZLM0eoeciUIGCSjbehi+1icExn2uxGFsdIHaiHjjz9sloOOsv6T+bGEYJiEPxiua+k3auFpHDfnJlrZOrXpBh0A2otI=
    file_glob: true
    file: dist/bin/sireg*
    skip_cleanup: true
    on:
      repo: FaKeller/sireg
      tags: true
  - provider: npm
    email: contact@fabian-keller.de
    api_key:
      secure: r0jDT6qGkmDMUMWZ/5SMyQshTEjCCahFWq8ezHckXHSXRduxtY7QLvqi3QsiIcgjF4flrXH1xDm3IyjTufrUeS6RD+ZZQHA1Tces5m+dtHzeynzAZJ8pDGttDku7DAeeE83mN4aTwXTrroyUWb10cQZwJyfzkgeZvsj3o46GQJDU6uuXAZS67FjGKnMAb2af/NPEb3yr+9NiwABMKpso+8mt4V2fCGAvdSSvEfW3LSBFe+NFSDbY2dTwvliFRRiD+VmMRAQe5n7HrYxIPiRLZYq1OmHecd70RksWnEud59FiS3YiedWFjPG67msMRrKuBvPiOQ2ZYsax6EtxeWte2HO4DPcUuITh+ywcIHo1CTlyz+5HYeqqC9zowl6xl2Wbj/bs/Lq8JOBYQZ31vqBq5e1Hk+XDNYQuawlp3XC+cfjPaMULP8NSY7H0isTJ5USIWtHFOu47dwy8XVQrTsSn2CSCUJXHqM3vtlhETFJ8NgSezvXz+02bxnaxHlHrLGA+VIInW5bCCpHYiapcdLPRvZHWVJosekEulHfxikuV/EX0Ek/Lx7qwkLuG/KTaMQg5FwM2x5L5tRHC2YnbHlV5mEjHwhgBPmZyYObaNzi+VuEl4MBI+sAj9QKmR7yAw1A/8uVkGXczWahDQGFcgNj33gBHggAr4NAKiGth0rGv7BY=
    on:
      repo: FaKeller/sireg
      tags: true
